export declare const center: string;
export declare const error: string;
export declare const left: string;
export declare const right: string;
export declare const root: string;
export declare const size_l: string;
export declare const size_m: string;
export declare const text: string;
export declare const title: string;
