export const root: string;
export const switchers: string;
export const lang: string;
export const button_collapsed: string;
export const items: string;
export const item: string;
export const link: string;
export const icon: string;
export const collapsed: string;
